apiVersion: v1
kind: ConfigMap
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        hosts /etc/coredns/customdomains.db blou.org {
          fallthrough
        }
        ready
        log . {
          class error
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . "/etc/resolv.conf"
        cache 30
        loop
        reload
        loadbalance
    }
  customdomains.db: |
    10.0.1.1 api.blou.com
    10.0.1.3 controller.blou.com
    10.0.1.4 master.nms.blou.com
    10.0.1.4 magma-test.nms.blou.com
    10.0.1.4 whatever.nms.blou.com

