name: main-branch

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  orchestrator-lint-report:
    name: Lint report
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: |
          set -eux
          charms="$(find ./orchestrator-bundle/ -name tox.ini)"
          for charm in ${charms}; do
            tox -c "${charm}" -e lint
          done

  orchestrator-static-analysis:
    name: Static analysis
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: |
          set -eux
          charms="$(find ./orchestrator-bundle/ -name tox.ini)"
          for charm in ${charms}; do
            tox -c "${charm}" -e static
          done

  orchestrator-unit-tests-with-coverage:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: |
          set -eux
          charms="$(find ./orchestrator-bundle/ -name tox.ini  -not -path "./orchestrator-bundle/orc8r-bundle/*")"
          for charm in ${charms}; do
            tox -c "${charm}" -e unit
          done

  orchestrator-integration-tests:
    name: Integration tests for bundle
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s

      - name: Enable metallb
        run: sudo microk8s enable metallb:10.1.1.1-10.1.1.10

      - name: Change /etc/hosts permissions
        run: sudo chmod a=rw /etc/hosts

      - name: Run integration tests
        run: cd orchestrator-bundle/orc8r-bundle && tox -e integration
