name: Upload charm orc8r-streamer-operator

on:
  push:
    branches:
      - "main"
    paths:
      - "orchestrator-bundle/orc8r-streamer-operator/**"

jobs:
  orc8r-streamer-charmhub-upload:
    runs-on: ubuntu-20.04
    name: Charmhub upload orc8r-streamer-operator
    steps:
      - uses: actions/checkout@v2

      - name: Check libraries
        uses: canonical/charming-actions/check-libraries@2.0.0-rc
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          charm-path: ./orchestrator-bundle/orc8r-streamer-operator

      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@2.0.0-rc
        id: channel

      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.0.0-rc
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          upload-image: "false"
          channel: "${{ steps.channel.outputs.name }}"
          charm-path: ./orchestrator-bundle/orc8r-streamer-operator
          tag-prefix: "magma-orc8r-streamer"
